apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-file-access
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-jacoco-file-access.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-jacoco-file-access.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: agents
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-agents
          readOnly: false
      - name: coverage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-coverage
          readOnly: false
      containers:
      - volumeMounts:
        - name: agents
          mountPath: /mnt/jacoco/agents
        - name: coverage
          mountPath: /mnt/jacoco/coverage
        name: reader
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['sleep', 'infinity']
      serviceAccountName: {{ include "k8s-jacoco-operator.serviceAccountName" . }}