apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jacoco-operator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jacoco-operator-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jacoco-operator-role
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-jacoco-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}